### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by gitjps** [IBM/cloud-native-starter#23]
The command

```
$ for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
hangs/does not return.
```

Couldn't validate the istio installation either:

```
$ istioctl verify-install
Error: unknown command "verify-install" for "istioctl"
Run 'istioctl --help' for usage.
```

**Comment by thomassuedbroecker** [comment]
We were able to solve to problem by following the steps prerequisites for the workshop: https://github.com/IBM/cloud-native-starter/blob/master/workshop/00-prerequisites.md#361-automated-creation-of-a-cluster-with-istio-for-the-workshop

**Comment by valters** [comment]
By the way it seems that a lot of information in documentation/IKSDeployment.md file is same as the 00-prerequisites.md, but 00-prerequisites.md is much more detailed (seems more up-to-date).

**Comment by Harald-U** [comment]
00-prerequisites.md is part of the workshop, was written much later than IKSDeployment.md and is, as part of a wokshop, much more detailled than IKSDeployment. IKSDeployment should still contain all relevant information. Did you find anything that is outright wrong or missing?

**Comment by valters** [comment]
No, the steps are identical. My concern is though they might go out of sync, maintaining information in two places at same time is really tricky to do :)

**Comment by thomassuedbroecker** [comment]
Hello Valters,

Thanks for your feedback!

The background to have two files is: the workshop 00-prerequisites.md is 
more detailed, because these prerequisites intended to support a hands-on 
workshop and does not include the deployment of the sample. 
The deployment of the sample is a task of the lab 02-container.md.

The ?normal? documentation is more for ?developers? and does not contain 
any detailed step and includes the deployment of the sample.

But your right, to maintain both takes additional effort from our side.

It seems you get your sample up and running or do you have a concrete 
problem?

Regards,

Thomas



Mit freundlichen Gruessen / with best regards,

Thomas Suedbroecker Dipl.Ing.(FH) 

Developer Advocate 
IBM Cognitive Applications 
IT Specialist Certification Experienced Level 




Phone: 49-170-4532365 
E-mail: thomas.suedbroecker@de.ibm.com 
Find me on:    


Altrottstraße 31 
Walldorf, 69190 
Germany



IBM Deutschland GmbH
Vorsitzender des Aufsichtsrats: Martin Jetter
Geschäftsführung: Matthias Hartmann (Vorsitzender), Norbert Janzen, Stefan 
Lutz, Nicole Reimer, Dr. Klaus Seifert, Wolfgang Wendt 
Sitz der Gesellschaft: Ehningen / Registergericht: Amtsgericht Stuttgart, 
HRB 14562 / WEEE-Reg.-Nr. DE 99369940

**Comment by valters** [comment]
I landed here because I am working through the instruction (I was at the workshop September 3.), and hit the `istioctl verify-install` issue. Doing a pull to get latest version of everything resolved it.

**Comment by thomassuedbroecker** [comment]
Hello Valters,

thanks for your information.

The Istio installation problem is mostly related to ( 
https://github.com/IBM/cloud-native-starter/issues/23).
That you are not logged on to the IBM Cloud and you don't have access to 
your cluster and install Istio.
We solved the problem in issue 22, by just be following the 00 steps from 
the beginning.

Based on your feedback I add the information "Ensure you are logged on to 
IBM Cloud in your terminal session."
 
https://github.com/IBM/cloud-native-starter/blob/master/workshop/00-prerequisites.md#46-create-a-ibm-cloud-kubernetes-service-and-add-istio


I hope that helps.

Regards, 

Thomas


Mit freundlichen Gruessen / with best regards,

Thomas Suedbroecker Dipl.Ing.(FH) 

Developer Advocate 
IBM Cognitive Applications 
IT Specialist Certification Experienced Level 




Phone: 49-170-4532365 
E-mail: thomas.suedbroecker@de.ibm.com 
Find me on:    


Altrottstraße 31 
Walldorf, 69190 
Germany



IBM Deutschland GmbH
Vorsitzender des Aufsichtsrats: Martin Jetter
Geschäftsführung: Matthias Hartmann (Vorsitzender), Norbert Janzen, Stefan 
Lutz, Nicole Reimer, Dr. Klaus Seifert, Wolfgang Wendt 
Sitz der Gesellschaft: Ehningen / Registergericht: Amtsgericht Stuttgart, 
HRB 14562 / WEEE-Reg.-Nr. DE 99369940
